Repository codelicia/turbo-enigma, pull requests merged in 2021-03, with the labels that each got.

#2 Use env vars for slack avatar and user name
  handlers.go
Labels: bug

#3 Refactor code to modules
  .github/workflows/main.yml
  main.go
  pkg/guard.go
  pkg/guard_test.go
  pkg/handlers.go
  pkg/handlers_test.go
  pkg/json_decode.go
  pkg/json_decode_test.go
  pkg/merge_request.go
  pkg/mocks.go
  pkg/payload.json
  pkg/post_json.go
Labels: enhancement

#4 Loop through env vars on guard.go
  pkg/guard.go
Labels: enhancement

#5 Filter out the very first event
  pkg/handlers.go
Labels: bug, enhancement

#9 Build image with a scratch base
  Dockerfile
Labels: enhancement

#12 Marshall JSON using marshaller to ensure chars are correctly escaped
  pkg/assert.go
  pkg/handlers.go
  pkg/handlers_test.go
  pkg/json_decode.go
  pkg/json_decode_test.go
  pkg/message/message.go
  pkg/message/slack.go
Labels: enhancement

#13 Report code coverage
  .github/workflows/main.yml
Labels: enhancement
